### ISSUE TITLE
0.3.6 - NoMethodError: undefined method `find' for Object:Class

### ISSUE THREAD

**Issue by antulik** [christospappas/streama#19]
Using mongoid 2.0. Works in steama 0.3.5, but not in 0.3.6.

```
NoMethodError: undefined method `find' for Object:Class
    from /Users/anton/.rvm/gems/ruby-1.9.3-p194@oddsense/gems/streama-0.3.6/lib/streama/activity.rb:90:in `load_instance'
    from /Users/anton/.rvm/gems/ruby-1.9.3-p194@oddsense/gems/streama-0.3.6/lib/streama/activity.rb:78:in `publish'
    from /Users/anton/.rvm/gems/ruby-1.9.3-p194@oddsense/gems/streama-0.3.6/lib/streama/activity.rb:55:in `publish'
    from /Users/anton/.rvm/gems/ruby-1.9.3-p194@oddsense/gems/streama-0.3.6/lib/streama/actor.rb:29:in `publish_activity'
    from (irb):3
```

did some debugging:

error happens here: https://github.com/christospappas/streama/blob/master/lib/streama/activity.rb#L90

``` ruby
    def load_instance(type)
      (data = self.read_attribute(type)).is_a?(Hash) ? data['type'].to_s.camelcase.constantize.find(data['id']) : data
    end
```

type == :actor
self.read_attribute(type) returns hash which has '_type' but no 'type' key.

After plain a bit more and reverting that line 
https://github.com/christospappas/streama/commit/9010eebb8f509567adfb717fbd4e0c0a630ce835#L2R11

to this: 

``` ruby
    field :actor,         :type => Hash
```

I have only actor but probably other fields will have the same issue.

Everything works after that reverted line. self.read_attribute(type) returns Object but not hash. Can't really explain that behaviour, but hopefully it will give you some ideas where to look.
